import type { Metadata } from "next";
import {Geist, Geist_Mono, Vazirmatn} from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazirMatn = Vazirmatn({
    variable:"--font-vazirmatn",
    subsets:["arabic"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirMatn.className}  antialiased`}
      >
      <Header/>
        {children}
      </body>
    </html>
  );
}
